dags:
  gitSync:
    enabled: true
    repo: "https://github.com"
    branch: "main"
    # Point this to the folder in your repo where the .py files live
    subPath: "kubernetes" 
    wait: 60
